-- AUTHORS tablosu: kitap yazarlari
CREATE TABLE authors (
    id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(200) NOT NULL
);

-- PUBLISHERS tablosu: yayinevleri
CREATE TABLE publishers (
    id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(200) NOT NULL
);

-- BOOKS tablosu: kitaplar (authors ve publishers'a foreign key ile bagli)
CREATE TABLE books (
    id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title        VARCHAR2(300) NOT NULL,
    author_id    NUMBER NOT NULL,
    publisher_id NUMBER NOT NULL,
    CONSTRAINT fk_book_author    FOREIGN KEY (author_id)    REFERENCES authors (id),
    CONSTRAINT fk_book_publisher FOREIGN KEY (publisher_id) REFERENCES publishers (id)
);

-- AUDIT_LOGS tablosu: kitap eklendiginde otomatik kayit tutar
CREATE TABLE audit_logs (
    id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name VARCHAR2(100),
    action     VARCHAR2(100),
    db_user    VARCHAR2(100),
    log_time   TIMESTAMP DEFAULT SYSTIMESTAMP
);